// Client Action Types
export const SET_USER = 'SET_USER';
export const SET_ROLES = 'SET_ROLES';
export const SET_THEME = 'SET_THEME';
export const SET_LANGUAGE = 'SET_LANGUAGE';

// Product Action Types
export const SET_CATEGORIES = 'SET_CATEGORIES';
export const SET_PRODUCTS = 'SET_PRODUCTS';
export const SET_TOTAL = 'SET_TOTAL';
export const SET_LOADING = 'SET_LOADING';
export const SET_ERROR = 'SET_ERROR';
export const SET_LIMIT = 'SET_LIMIT';
export const SET_OFFSET = 'SET_OFFSET';
export const SET_FILTER = 'SET_FILTER';
export const SET_PRODUCT_CATEGORY_ID = 'SET_PRODUCT_CATEGORY_ID';
export const SET_PRODUCT_SORT = 'SET_PRODUCT_SORT';
export const SET_PRODUCT_FILTER = 'SET_PRODUCT_FILTER';
export const SET_PRODUCT_DETAIL = 'SET_PRODUCT_DETAIL';
export const FETCH_PRODUCT_DETAIL_START = 'FETCH_PRODUCT_DETAIL_START';
export const FETCH_PRODUCT_DETAIL_SUCCESS = 'FETCH_PRODUCT_DETAIL_SUCCESS';
export const FETCH_PRODUCT_DETAIL_FAILURE = 'FETCH_PRODUCT_DETAIL_FAILURE';

// Shopping Cart Action Types
export const SET_CART = 'SET_CART';
export const SET_PAYMENT = 'SET_PAYMENT';
export const SET_ADDRESS = 'SET_ADDRESS';
export const ADD_TO_CART = 'ADD_TO_CART';
export const INCREASE_CART_ITEM_COUNT = 'INCREASE_CART_ITEM_COUNT';
export const DECREASE_CART_ITEM_COUNT = 'DECREASE_CART_ITEM_COUNT';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const TOGGLE_CART_ITEM_CHECKED = 'TOGGLE_CART_ITEM_CHECKED';
export const SET_ALL_CART_ITEMS_CHECKED_BY_SELLER = 'SET_ALL_CART_ITEMS_CHECKED_BY_SELLER'; 